FROM java:8
VOLUME /tmp/tomcat
ADD gateway-0.0.1-SNAPSHOT.jar gateway.jar
ENTRYPOINT ["java","-Xms10m","-Xmx100m","-XX:MetaspaceSize=120m","-XX:MaxMetaspaceSize=240m","-Djava.security.egd=file:/dev/./urandom","-jar","/gateway.jar"]