FROM java:8
VOLUME /tmp/tomcat
ADD contentcenter-0.0.1-SNAPSHOT.jar contentcenter.jar
ENTRYPOINT ["java","-Xms10m","-Xmx100m","-XX:MetaspaceSize=120m","-XX:MaxMetaspaceSize=240m","-Djava.security.egd=file:/dev/./urandom","-jar","/contentcenter.jar"]