apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-pc-operatecenter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-pc-operatecenter
  template:
    metadata:
      labels:
        app: java-pc-operatecenter
    spec:
      containers:
        - name: java-pc-operatecenter
          image: ${ORIGIN_REPO}/${REPO}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8915
          resources:
            requests:
              memory: 1024Mi
            limits:
              memory: 2048Mi
          livenessProbe:
            tcpSocket:
              port: 8915
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health?value=k8s
              port: 8915
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 1
            successThreshold: 1
            timeoutSeconds: 5
          env:
            - name: aliyun_logs_catalina
              value: "stdout"
            - name: aliyun_logs_prod-pc-operatecenter-roll
              value: "/var/log/gfs-logs/*.log"
          volumeMounts:
            - mountPath: /var/log/gfs-logs/
              name: java-pc-operatecenter
      volumes:
        - name: java-pc-operatecenter
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: java-pc-operatecenter
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8915
  selector:
    app: java-pc-operatecenter
  sessionAffinity: None
  type: ClusterIP